project:
  type: website
  output-dir: docs

website:
  title: "KrisanatA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: software.qmd
        text: Software
      - href: ebs-network.qmd
        text: EBS Network
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
  page-footer:
    border: false
    left: "© 2026 Krisanat Anukarnsakulchularp"
    right: "Built with Quarto"

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: true

