project:
  type: website
  output-dir: docs

website:
  title: "KrisanatA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: software.qmd
        text: Software
      - href: cv.qmd
        text: CV

format:
  html:
    theme: Morph
    css: styles.css
    toc: true



